trigger:
- develop

stages:
- stage: build

  jobs:
  - job: run
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: dotnet run
      displayName: Build and run 
      workingDirectory: ./SimpleConsoleApp